publish_frequency: 5.0
update_frequency: 12.0
width: 10.0
height: 10.0
resolution: 0.1
origin_x: 0.0
origin_y: 0.0
global_frame: odom_combined
robot_base_frame: base_link
footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]
footprint_padding: 0.05
rolling_window: true
plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: obstacles, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater, type: "costmap_2d::InflationLayer"}
  - {name: human_layer_static, type: "cohan_layers::StaticAgentLayer"}

obstacles:
  observation_sources: /base_scan
  /base_scan: {data_type: LaserScan, sensor_frame: base_laser_link, expected_update_rate: 0.3, marking: true, clearing: true}
  footprint_clearing_enabled: true
inflater:
  inflation_radius: 0.2
# static:
#   enabled:              true
#   map_topic:            "/map"
# human_layer_static:
#   robot_radius: 0.46
#   agent_radius: 0.31
