local_costmap:
  global_frame: odom_combined
  robot_base_frame: base_link
  update_frequency: 12.0
  publish_frequency: 5.0
  width: 10.0
  height: 10.0
  rolling_window: true
  origin_x: 0
  origin_y: 0
  robot_radius: 0.3
  # footprint: [[-0.325, -0.325], [-0.325, 0.325], [0.325, 0.325], [0.46, 0.0], [0.325, -0.325]]


  plugins:
  - {name: static, type: "costmap_2d::StaticLayer"}
  - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
  - {name: inflater_layer, type: "costmap_2d::InflationLayer"}
